# Generated by Django 4.2.3 on 2023-09-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("owner_uuid", models.UUIDField(null=True)),
            ],
        ),
    ]
