# Generated by Django 4.2.3 on 2023-09-12 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books_ddd", "0002_bookorm"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
